**420-SF2-RE: DS & OOP**

**February 12, 2025**

# Assignment #1: drag with coffee filters

For this assignment you will be allowed to use everything that has been covered in class regarding data science libraries.  **Any functions not covered in class will not be allowed to be used and will receive a grade of 0**. 

${\color{red}\text{You should not be making any direct changes to your .csv files.}}\\$
${\color{red}\text{All changes done in this assignment must be done using Python code.}}$

## Part 1: experiment with single coffee filter, 10 runs
**Part 1 DUE DATE: end of class today**

**Part 1 is worth 60% of Assignment #1**

**Part 1 of the assignment is an in-class assignment.  Failure to be in class will receive a grade of 0 for Part 1 of the assignment and late submissions will not be accepted.**


#### Submission: 
- Upload all new and updated files to moodle under ${\color{green}\text{Assignment \#1}}$
- `add`, `commit`, `push` all new and updated files to ${\color{green}\text{git}}$ in your **Assignment #1** folder
- Late submissions of Part 1 (that is, submissions outside of class) will receive a ${\color{red}\text{late penalty}}$. Part 1 may not be submitted later than **Wendesday, February 12 ay 23:59**.

#### Instructions for Part 1:

1. Import all necessary libraries, such as `pandas`, `matplotlib.pyplot`, `numpy`, etc.

In [1]:
# your code for step 1 goes here:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

2. Read  your `.csv` file that has the data of the single filter experiment into a DataFrame called `df`
3. Display the content of the data frame to the screen

In [ ]:
# your code for steps 2 and 3 go here:
df = pd.read_csv('10x1 Data.csv')

df

     Time (s) Run #1  Position (m) Run #1  Velocity (m/s) Run #1  \
0               0.00                  1.3                    NaN
1               0.02                  1.3                  -0.01
2               0.04                  1.3                   0.00
3               0.06                  1.3                   0.01
4               0.08                  1.3                   0.01
..               ...                  ...                    ...
130              NaN                  NaN                    NaN
131              NaN                  NaN                    NaN
132              NaN                  NaN                    NaN
133              NaN                  NaN                    NaN
134              NaN                  NaN                    NaN

     Acceleration (m/s²) Run #1  Time (s) Run #2  Position (m) Run #2  \
0                           NaN             0.00                 1.24
1                           NaN             0.02                 1.24
2                          0.65             0.04                 1.24
3                          0.25             0.06                 1.23
4                          0.06             0.08                 1.23
..                          ...              ...                  ...
130                         NaN              NaN                  NaN
131                         NaN              NaN                  NaN
132                         NaN              NaN                  NaN
133                         NaN              NaN                  NaN
134                         NaN              NaN                  NaN

     Velocity (m/s) Run #2  Acceleration (m/s²) Run #2  Time (s) Run #3  \
0                      NaN                         NaN             0.00
1                    -0.08                         NaN             0.02
2                    -0.11                       -0.44             0.04
3                    -0.09                        1.64             0.06
4                    -0.02                        2.49             0.08
..                     ...                         ...              ...
130                    NaN                         NaN              NaN
131                    NaN                         NaN              NaN
132                    NaN                         NaN              NaN
133                    NaN                         NaN              NaN
134                    NaN                         NaN              NaN

     Position (m) Run #3  ...  Velocity (m/s) Run #8  \
0                   1.24  ...                    NaN
1                   1.24  ...                   0.01
2                   1.24  ...                   0.03
3                   1.24  ...                   0.05
4                   1.24  ...                   0.05
..                   ...  ...                    ...
130                  NaN  ...                    NaN
131                  NaN  ...                    NaN
132                  NaN  ...                    NaN
133                  NaN  ...                    NaN
134                  NaN  ...                    NaN

     Acceleration (m/s²) Run #8  Time (s) Run #9  Position (m) Run #9  \
0                           NaN             0.00                 1.05
1                           NaN             0.02                 1.05
2                          1.15             0.04                 1.06
3                          0.31             0.06                 1.06
4                         -0.45             0.08                 1.06
..                          ...              ...                  ...
130                         NaN              NaN                  NaN
131                         NaN              NaN                  NaN
132                         NaN              NaN                  NaN
133                         NaN              NaN                  NaN
134                         NaN              NaN                  NaN

     Velocity (m/s) Run #9  Acceleration (m/s²) Run #9  Time (s) Run #10  \
0                      NaN                         NaN              0.00
1                     0.05                         NaN              0.02
2                     0.10                        0.91              0.04
3                     0.08                       -0.69              0.06
4                     0.04                       -0.87              0.08
..                     ...                         ...               ...
130                    NaN                         NaN               NaN
131                    NaN                         NaN               NaN
132                    NaN                         NaN               NaN
133                    NaN                         NaN               NaN
134                    NaN                         NaN               NaN

     Position (m) Run #10  Velocity (m/s) Run #10  Acceleration (m/s²) Run #10
0                    1.05                     NaN                          NaN
1                    1.04                    0.08                          NaN
2                    1.05                    0.19                         3.86
3                    1.05                    0.24                        -2.17
4                    1.06                    0.11                        -6.25
..                    ...                     ...                          ...
130                   NaN                     NaN                          NaN
131                   NaN                     NaN                          NaN
132                   NaN                     NaN                          NaN
133                   NaN                     NaN                          NaN
134                   NaN                     NaN                          NaN

[135 rows x 40 columns]

4. Extract from the DataFrame `df` into a new DataFrame `data_df` only the **Time** and **Position** columns for the 10 runs.  Here are the details of how your `data_df` should look: 
- Time column titles should read: **Time (s) Run #$i$** for $0\leq i\leq 10$
- Position column titles should read: **Position (m) Run #$i$** for $0\leq i\leq 10$
- The order of the columns in your `data_df` should first display all the **Time** columns then all the **Position** columns.  
- all NaN values should be dropped from `data_df`
Note that this process should be automated.  You **should not** manually adjust the content of the `data_df` for each run. 
5. Display the content of `data_df`

In [ ]:
# Your code for steps 4 and 5 go here:
times = []
pos = []
for i in range (1,11):
    times.append(f'Time (s) Run #{i}')
    pos.append(f'Position (m) Run #{i}')

data_df = df[times + pos]
data_df.dropna() # NOTE: HELP
data_df

,Time (s) Run #1,Time (s) Run #2,Time (s) Run #3,Time (s) Run #4,Time (s) Run #5,Time (s) Run #6,Time (s) Run #7,Time (s) Run #8,Time (s) Run #9,Time (s) Run #10,Position (m) Run #1,Position (m) Run #2,Position (m) Run #3,Position (m) Run #4,Position (m) Run #5,Position (m) Run #6,Position (m) Run #7,Position (m) Run #8,Position (m) Run #9,Position (m) Run #10
0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1.3,1.24,1.24,1.28,1.22,1.08,1.07,1.07,1.05,1.05
1,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,1.3,1.24,1.24,1.28,1.20,1.08,1.06,1.07,1.05,1.04
2,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,1.3,1.24,1.24,1.28,1.20,1.08,1.06,1.07,1.06,1.05
3,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06,1.3,1.23,1.24,1.28,1.22,1.07,1.06,1.07,1.06,1.05
4,0.08,0.08,0.08,0.08,0.08,0.08,0.08,0.08,0.08,0.08,1.3,1.23,1.24,1.28,1.20,1.07,1.06,1.07,1.06,1.06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130,NaN,NaN,NaN,NaN,2.60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.83,NaN,NaN,NaN,NaN,NaN
131,NaN,NaN,NaN,NaN,2.62,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.82,NaN,NaN,NaN,NaN,NaN
132,NaN,NaN,NaN,NaN,2.64,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.84,NaN,NaN,NaN,NaN,NaN
133,NaN,NaN,NaN,NaN,2.66,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.84,NaN,NaN,NaN,NaN,NaN
134,NaN,NaN,NaN,NaN,2.68,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.84,NaN,NaN,NaN,NaN,NaN

6. The data in `data_df` contains noisy data.  In this step you are to clean the noisy data (or extract the clean data). Your cleaned data **for each run**
- must not include the data that is after once the filter hits the motion sensor
- must include the curved data that transitions into a drop in position.  You should only keep about 0.5 to 1 second of the roughly constant position values before the drop of position takes place.  
Note that you should clean your data for each of the 10 runs and you should automate this process in your code with logical conditions, loops, etc.

7. Store your clean data into a new DataFrame called `clean_df`. 
8. Note that now that the values in the **Time** columns may have shifted due to the clean-up.  Update your `clean_df` to rescale all the **Time** columns to start the time from 0.0 in increments of 0.02. 
9. Write this to a new .csv file called `"clean_data_single_filter.csv"`.

In [ ]:
# Your code for steps 6-9 go here:
KEEP = 0.5
clean_df = pd.DataFrame()
for i in range(1, 11):
    run_df = data_df[[f'Time (s) Run #{i}', f'Position (m) Run #{i}']].dropna()
    min_index = run_df[f'Position (m) Run #{i}'].idxmin()
    max_index = run_df[f'Position (m) Run #{i}'][:min_index].idxmax()
    max_time = run_df[f'Time (s) Run #{i}'][max_index]
    run_df = run_df[(run_df[f'Time (s) Run #{i}'] > max_time - KEEP) & (run_df.index <= min_index)]
    clean_df = pd.concat([clean_df, run_df])

clean_df

,Time (s) Run #1,Position (m) Run #1,Time (s) Run #2,Position (m) Run #2,Time (s) Run #3,Position (m) Run #3,Time (s) Run #4,Position (m) Run #4,Time (s) Run #5,Position (m) Run #5,Time (s) Run #6,Position (m) Run #6,Time (s) Run #7,Position (m) Run #7,Time (s) Run #8,Position (m) Run #8,Time (s) Run #9,Position (m) Run #9,Time (s) Run #10,Position (m) Run #10
0,0.00,1.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.02,1.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0.04,1.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0.06,1.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0.08,1.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.52,0.22
77,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.54,0.16
78,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.56,0.13
79,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.58,0.13
80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.60,0.12

10. Plot the data using `matplotlib` from all 10 runs as scatter plots on the same figure using your cleaned data.  
- Each plot should have a label **Run #$i$** for $1\leq i\leq10$
- The label on the x-axis should read **Time (s)**
- The label on the y-axis should read **Position (m)**
- Each plot should be in a different color and there should be a legend showing which colour is which run. 
- scale the size of the points so that they are not too big.  
Note that you should automate the process of plotting the 10 graphs.

11. Take the last 0.5 to 1 second of the x-values in your 10 runs, and draw a line of best fit on all your 10 graphs.

In [ ]:
# Your code for steps 10-11 go here:

### ${\color{green} \text{Submit your work to moodle and git for Part 1 before moving to Part 2}}$

## Part 2: experiment with multiple coffee filters, 10 runs
**Part 2 DUE DATE: Friday, February 14 at 20:00**

**Part 2 is worth 40% of Assignment #1**

#### Submission:
- Upload all new and updated files to moodle under ${\color{green}\text{Assignment \#1}}$.  Make sure to not delete or overwrite any files during your previous submissions.  
- `add`, `commit`, `push` all new and updated files to ${\color{green}\text{git}}$ in your **Assignment #1** folder
- late submissions of Part 2 will receive a grade of 0.


#### Instructions for Part 2:

1. Read  your .csv file that has the data of filters of varying mass into a DataFrame `df`.  
3. Display the content of the DataFrame to the screen

In [ ]:
# Your code for steps 1 and 2 go here:

3. Extract from the DataFrame `df` into a new DataFrame `data_df` only the **Time** and **Position** columns for the 10 runs.  Here are the details of how your `data_df` should look: 
- Time column titles should read: **Time (s) Run #$i$** for $0\leq i\leq 10$
- Position column titles should read: **Position (m) Run #$i$** for $0\leq i\leq 10$
- The order of the columns in your `data_df` should first display all the **Time** columns then all the **Position** columns.  
- all NaN values should be dropped from `data_df`
Note that this process should be automated.
4. Display the content of `data_df`

In [ ]:
# Your code for steps 3 and 4 go here:

5. The data in `data_df` contains noisy data.  In this step you are to clean the noisy data (or extract the clean data). Your cleaned data **for each run**
- must not include the data that is after once the filter hits the motion sensor
- must include only the bit where a drop in position starts.  You should not include any constant position values before the drop of positions takes place.    
Note that you should clean your data for each of the 10 runs and you should automate this process in your code with logical conditions, loops, etc.
6. Store your clean data into a new DataFrame called `clean_df`. 
7. Note that now that the values in the **Time** columns may have shifted due to the clean-up.  Update your `clean_df` to rescale all the **Time** columns to start the time from 0.0 in increments of 0.02. 
8. Write this to a new .csv file called `"clean_data_multiple_filter.csv"`.

In [ ]:
# Your code for steps 5-8 go here:

9. Plot the data from all 10 runs as line plots on the same figure using your cleaned data.  
- Each plot should have a label **Run #$i$** for $1\leq i\leq10$
- The label on the x-axis should read **Time (s)**
- The label on the y-axis should read **Position (m)**
- Each plot should be in a different color and there should be a legend showing which colour is which run.

In [ ]:
# Your code for step 9 goes here: